kiauh.sh
scripts/backup.sh
scripts/functions.sh
scripts/install_klipperscreen.sh
scripts/remove.sh
scripts/status.sh
scripts/ui/backup_menu.sh
scripts/ui/install_menu.sh
scripts/ui/main_menu.sh
scripts/ui/remove_menu.sh
scripts/ui/update_menu.sh
scripts/update.sh

Add functions to support KlipperScreen installation/removal/updating from kiauh

Add KlipperScreen to kiauh

---

scripts/install_klipper.sh

Slighty less confusing for new users.

install_klipper.sh prompt phrasing

---

resources/gcode_shell_command.py

Without clearing the partial line on a full line being sent the self.partial_output was repeated for every subsequent line.

Fix issue with partial lines being repeated

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Signed-off-by: Pedro Lamas <pedrolamas@gmail.com>

github: adds GitHub issue templates

---

scripts/fluidd.sh
scripts/klipper.sh
scripts/klipperscreen.sh
scripts/mainsail.sh
scripts/moonraker-telegram-bot.sh
scripts/moonraker.sh
scripts/nginx.sh
scripts/pretty_gcode.sh
scripts/ui/update_menu.sh
scripts/utilities.sh

full rework of the update-all routine
there is still some kind of performance issue that makes loading the update menu a bit slower than pre-version 4.
this needs to be addressed in another PR.
Signed-off-by: Dominik Willner th33xitus@gmail.com

fix: update all function (#204)

---

scripts/fluidd.sh
scripts/mainsail.sh

fix: typo in mjpg-streamer dialog

---

docs/changelog.md
resources/moonraker-telegram-bot.env
resources/moonraker-telegram-bot.service
scripts/moonraker-telegram-bot.sh
scripts/ui/install_menu.sh

this PR will update the telegram bot installer to adapt the recent moonraker changes

refactor(telegram-bot): update telegram-bot installer

---

docs/changelog.md
scripts/klipper.sh
scripts/obico.sh
scripts/ui/install_menu.sh
scripts/utilities.sh

refactor(obico): update obico installer

---

resources/klipper.service
scripts/klipper.sh
scripts/ui/install_menu.sh

refactor(klipper): full refactor of klipper install/remove part

---

docs/changelog.md
scripts/crowsnest.sh
scripts/globals.sh
scripts/ui/install_menu.sh
scripts/ui/main_menu.sh
scripts/ui/remove_menu.sh
scripts/ui/update_menu.sh

Signed-off-by: Stephan Wendel <me@stephanwe.de>

feat: replace mjpg-streamer with crowsnest

---

scripts/fluidd.sh
scripts/ui/remove_menu.sh

I based these changes on the existing mainsail.sh, I think I got them all and seems to be working fine

feat(fluidd): use fluidd-config repo for downloading fluidd macros

---

scripts/klipper.sh
scripts/moonraker.sh
scripts/octoprint.sh
scripts/utilities.sh

refactor(klipper): implement blacklisted service names

---

scripts/crowsnest.sh

This should improve search performance to determine install status of crowsnest

refactor(crowsnest): improve performance in crowsnest.sh

---

README.md
scripts/globals.sh
scripts/octoeverywhere.sh
scripts/ui/install_menu.sh
scripts/ui/main_menu.sh
scripts/ui/remove_menu.sh
scripts/ui/update_menu.sh

We are excited that OctoEverywhere for Klipper is here! 
I have carefully added OctoEverywhere into the system. I did full testing of install, remove, and update. The one non-standard thing I did was to block updates from the UI, since it's possible that future OE updates might need system dependencies and python package updates, which Kiauh doesn't handle, but the moonraker update manager does.
Please let me know if I missed anything! I'm happy to do any more work required to finish this up!

feat: add OctoEverywhere for Klipper

---

scripts/octoeverywhere.sh
scripts/ui/update_menu.sh

Since OctoEverywhere can now update via the update command, I added the few last things to all it to be part of the update all action.

feat(octoeverywhere): add OE to the "update all" action

---

scripts/mainsail.sh

update url of the themes.csv file to the new mainsail docs

refactor(mainsail): update themes.csv url for mainsail themes

---

scripts/fluidd.sh
scripts/mainsail.sh

fix(mainsail/fluidd): fall back to latest stable url if fetching tags fails

---

README.md

Hi @th33xitus,
This is a minor update to the README.md to correct several typos, purely for aesthetic purposes.
Thank you for your work! :)

readme: fix typos in README.md

---

scripts/klipper.sh

feat(klipper): remove/disable brltty and ModemManager during installation

---

scripts/flash_klipper.sh

Signed-off-by: Andrei Kozhevnikov <coderusinbox@gmail.com>

feat(advanced): add selection between flash/serialflash methods

---

scripts/mobileraker.sh

This reverts commit ba1cdb37395dd0db2a752f68436e929c27c6ea55.

fix: revert "refactor(Mobileraker): update companion install script (#431)"

---

scripts/mobileraker.sh

@Clon1998 I created this new PR, that will be merged once you are ready on your side. Please let me know. Sorry again!

refactor(Mobileraker): update companion install script (#431)

---

README.md
scripts/globals.sh
scripts/octoapp.sh
scripts/ui/install_menu.sh
scripts/ui/main_menu.sh
scripts/ui/remove_menu.sh
scripts/ui/update_menu.sh

This PR adds support for OctoApp. I modified:
- Main menu to reflect OctoApp
- Update menu to reflect OctoApp
- Remove menu to reflect OctoApp
- Redme
My scripts are copied and modified from the OctoEverywhere ones, as my plugin is a fork of OctoEverywhere

feat: add OctoApp support

---

kiauh/extensions/klipper_backup/klipper_backup_extension.py

The old test branch will be deleted anyway

chore: remove test section and add new klipperbackup url in header

---

kiauh/extensions/klipper_backup/__init__.py
kiauh/extensions/klipper_backup/klipper_backup_extension.py

My solution was a bit hackish anyway

refactor(klipper_backup): replace is_service_installed with service_instance_exists

---

README.md

readme: fix broken OctoApp plugin link

---

kiauh/extensions/klipper_backup/klipper_backup_extension.py

Klipper-Backup extension now
- supports the new unit check function
- is using `SYSTEMD` variable instead of hardcoded `/etc/systemd/system` path
- is running `sudo systemctl reset-failed` after uninstalling systemd services/timer to reset all units with failed status 
- code generally revised / beautified in small sections

refactor(extension): add new check to klipper backup extension

---

kiauh/extensions/klipper_backup/klipper_backup_extension.py

Fix'd some mistakes in old code (removed unnecessary lines, beautify code, add missing functions, replaced self-written code lines with KIAUH functions, etc.)

refactor(extension): Adjust code in Klipper-Backup

---

kiauh/core/backup_manager/backup_manager.py
kiauh/core/menus/main_menu.py
kiauh/core/menus/settings_menu.py
kiauh/core/settings/kiauh_settings.py
kiauh/core/types.py
kiauh/procedures/switch_repo.py
kiauh/utils/common.py
kiauh/utils/git_utils.py
kiauh/utils/sys_utils.py

Extend the functionality of repo switching by creating a backup before the switch. Also implement a rollback mechanic in case of an error.
Fixes #512 

fix: fix switching of repositories

---

kiauh/components/klipperscreen/klipperscreen.py
kiauh/extensions/telegram_bot/moonraker_telegram_bot_extension.py

fix: typo in "origin" and "managed_services"

---

kiauh/components/klipperscreen/klipperscreen.py
kiauh/core/backup_manager/backup_manager.py
kiauh/core/menus/main_menu.py
kiauh/core/menus/settings_menu.py
kiauh/core/settings/kiauh_settings.py
kiauh/core/types.py
kiauh/extensions/telegram_bot/moonraker_telegram_bot_extension.py
kiauh/procedures/switch_repo.py
kiauh/utils/common.py
kiauh/utils/git_utils.py
kiauh/utils/sys_utils.py

Fixes https://github.com/dw-0/kiauh/issues/512
Fixes https://github.com/dw-0/kiauh/issues/515

Merge develop into master

---

kiauh.sh

fix: run umask 022 at launch

---

kiauh/core/menus/main_menu.py
kiauh/utils/common.py

fix: trunc owner and repo name if they would overflow

---

kiauh/core/menus/update_menu.py

feat: implement update all feature

---

kiauh/core/submodules/simple_config_parser/src/simple_config_parser/simple_config_parser.py
kiauh/core/submodules/simple_config_parser/tests/assets/test_config_2.cfg
kiauh/core/submodules/simple_config_parser/tests/assets/test_config_3.cfg
kiauh/core/submodules/simple_config_parser/tests/line_parsing/test_line_parsing.py
kiauh/core/submodules/simple_config_parser/tests/public_api/conftest.py
kiauh/core/submodules/simple_config_parser/tests/public_api/test_options_api.py
kiauh/core/submodules/simple_config_parser/tests/public_api/test_sections_api.py
kiauh/core/submodules/simple_config_parser/tests/value_conversion/test_get_conv.py
kiauh/utils/config_utils.py

Merge develop into master (v6.0.0-alpha.5)

---

kiauh/extensions/telegram_bot/assets/moonraker-telegram-bot.service
kiauh/extensions/telegram_bot/moonraker_telegram_bot_extension.py
kiauh/utils/sys_utils.py

fix: allow moonraker-telegram-bot-env access to systems site-packages dir

---

kiauh/components/klipper_firmware/firmware_utils.py

fix: correctly find connected USB DFU devices

---

kiauh/components/klipper_firmware/firmware_utils.py

fix: correctly find connected UART devices

---

kiauh/core/constants.py
kiauh/extensions/extensions_menu.py
kiauh/extensions/simply_print/metadata.json
kiauh/extensions/simply_print/simply_print_extension.py
kiauh/utils/common.py

feat: add SimplyPrint extension

---

kiauh/utils/git_utils.py

fix: always return string tuple from get_repo_name()

---

.gitignore
kiauh/components/webui_client/client_utils.py

fix: correctly handle IPs in nginx config files when parsing ports

---

.gitignore
kiauh/components/webui_client/client_utils.py
kiauh/core/constants.py
kiauh/extensions/extensions_menu.py
kiauh/extensions/octoapp/__init__.py
kiauh/extensions/octoapp/octoapp_extension.py
kiauh/extensions/simply_print/metadata.json
kiauh/extensions/simply_print/simply_print_extension.py
kiauh/utils/common.py
kiauh/utils/git_utils.py

fixes #561 
fixes #564 
fixes #565

Merge develop into master (v6.0.0-alpha.7)

---

scripts/spoolman.sh

fix(KIAUH v5): correctly add Spoolman to moonraker.asvc

---

default.kiauh.cfg
kiauh/components/webui_client/client_dialogs.py
kiauh/components/webui_client/client_setup.py
kiauh/components/webui_client/client_utils.py

refactor: do not silently configure Fluidd for port 81

---

default.kiauh.cfg
kiauh/components/klipper_firmware/firmware_utils.py
kiauh/components/klipper_firmware/flash_options.py
kiauh/components/klipper_firmware/menus/klipper_flash_help_menu.py
kiauh/components/klipper_firmware/menus/klipper_flash_menu.py
kiauh/components/webui_client/client_dialogs.py
kiauh/components/webui_client/client_setup.py
kiauh/components/webui_client/client_utils.py
scripts/spoolman.sh

Merge develop into master (Release v6.0.0-alpha.8)

---

kiauh/components/webui_client/client_config/client_config_setup.py
kiauh/components/webui_client/client_dialogs.py
kiauh/components/webui_client/client_setup.py
kiauh/components/webui_client/client_utils.py
kiauh/components/webui_client/menus/client_install_menu.py
kiauh/core/menus/install_menu.py
kiauh/utils/config_utils.py

feat: implement port reconfiguration for webclients

---

kiauh.py

fix: make sure all output is utf-8 encoded

---

kiauh/core/menus/settings_menu.py
kiauh/core/types.py
kiauh/utils/common.py
kiauh/utils/git_utils.py

feat: show actual current branch in settings menu

---

kiauh.py
kiauh.sh
kiauh/components/webui_client/client_config/client_config_setup.py
kiauh/components/webui_client/client_dialogs.py
kiauh/components/webui_client/client_setup.py
kiauh/components/webui_client/client_utils.py
kiauh/components/webui_client/menus/client_install_menu.py
kiauh/core/menus/base_menu.py
kiauh/core/menus/install_menu.py
kiauh/core/menus/settings_menu.py
kiauh/core/types.py
kiauh/utils/common.py
kiauh/utils/config_utils.py
kiauh/utils/git_utils.py

fixes #509 
fixes #514
fixes #576 
fixes #585

Merge develop into master (Release v6.0.0-alpha.9)

---

kiauh/components/crowsnest/crowsnest.py
scripts/crowsnest.sh

refactor: remove `BASE_USER` argument from crowsnest install command

---

kiauh/components/webui_client/client_setup.py

refactor: omit port 80 for IP in success message after webclient installation

---

kiauh/components/crowsnest/crowsnest.py
kiauh/components/klipper/__init__.py
kiauh/components/klipper_firmware/firmware_utils.py
kiauh/components/klipper_firmware/flash_options.py
kiauh/components/klipper_firmware/menus/klipper_build_menu.py
kiauh/components/klipper_firmware/menus/klipper_flash_menu.py
kiauh/components/moonraker/moonraker_setup.py
kiauh/components/moonraker/moonraker_utils.py
kiauh/components/webui_client/client_setup.py
kiauh/core/menus/advanced_menu.py
kiauh/procedures/system.py
kiauh/utils/sys_utils.py
scripts/crowsnest.sh

fixes #607 
fixes #615
fixes #618 
fixes #619 
fixes #620 
fixes #623 
fixes #627

Merge develop into master (Release v6.0.0-alpha.14)

---

kiauh/components/moonraker/moonraker_setup.py
kiauh/utils/sys_utils.py

fix(moonraker): use os-release file to get distro info

---

kiauh/components/moonraker/moonraker_setup.py
kiauh/utils/sys_utils.py
resources/moonraker.conf

Merge develop into master (Release v6.0.0-alpha.15)

---

kiauh/components/moonraker/moonraker_setup.py
kiauh/components/moonraker/utils/sysdeps_parser.py
kiauh/components/moonraker/utils/utils.py
kiauh/core/menus/backup_menu.py
kiauh/core/menus/main_menu.py
kiauh/core/menus/settings_menu.py
kiauh/core/menus/update_menu.py

fix(moonraker): adapt to new moonraker system_dependency.json syntax

---

kiauh/components/klipper/klipper_utils.py
kiauh/core/menus/advanced_menu.py
kiauh/utils/sys_utils.py

feat(advanced): install input shaper dependencies

---

.editorconfig
kiauh/components/klipper_firmware/menus/klipper_flash_menu.py
kiauh/components/webui_client/client_utils.py
kiauh/extensions/pretty_gcode/pretty_gcode_extension.py
kiauh/extensions/spoolman/__init__.py
kiauh/extensions/spoolman/assets/docker-compose.yml
kiauh/extensions/spoolman/metadata.json
kiauh/extensions/spoolman/spoolman.py
kiauh/extensions/spoolman/spoolman_extension.py
kiauh/utils/input_utils.py
kiauh/utils/sys_utils.py

feat(extension): add Spoolman Docker installer

---

default.kiauh.cfg
kiauh/components/klipper/services/klipper_setup_service.py
kiauh/components/moonraker/services/moonraker_setup_service.py
kiauh/core/settings/kiauh_settings.py
kiauh/utils/sys_utils.py

Implement changes discussed in https://github.com/dw-0/kiauh/issues/670

feat: add option to customize python binary for Klipper and Moonraker, add option to not install Moonraker speedups

---

kiauh/utils/sys_utils.py
scripts/klipper.sh
scripts/moonraker.sh

pip 25 seems to introduce some compatibility issues.

fix: do not upgrade pip before installing packages

---

scripts/klipperscreen.sh
scripts/mobileraker.sh

Fix a couple of typos in the messages.

chore: fix typos
