dw-0/kiauh

scripts/status.sh

Old `ls /etc/systemd/system | grep 'moonraker'` can count as a service other moonraker clients.
```
pi@raspberrypi:~ $ ls /etc/systemd/system | grep 'moonraker'
moonraker-1.service
moonraker-2.service
moonraker-telegram-bot.service
```
So this commit makes it work correctly
```
pi@raspberrypi:~ $ ls /etc/systemd/system | grep -E 'moonraker\.service|moonraker-[[:digit:]]*.service'
moonraker-1.service
moonraker-2.service
```

More accurate moonraker service search

---

scripts/install_mjpg-streamer.sh

Fixes script src links to allow mjpg-streamer service to start
Script had outdated links resulting in 404's

Issue 85 fix

---

scripts/ui/advanced_menu.sh
scripts/ui/backup_menu.sh
scripts/ui/general_ui.sh
scripts/ui/install_menu.sh
scripts/ui/remove_menu.sh
scripts/ui/settings_menu.sh
scripts/ui/update_menu.sh
scripts/upload_log.sh

When I first ran the code, I went to advanced because I had klipper already installed and I wanted to see if I could install fluidd using this code base. So when see advanced menu I was concerned that "quit" meant quitting the tool instead of exiting the advanced menu. So proposing a back_footer for sub menus that will revert back to main menu. You would use the quit footer for main menu to exit program.
changed submenus to use back_footer
edited general_ui to add back_footer as a UI component

PR Submenu change from "quit" to "back"

---

resources/webcamd.service

Related to [Issue#127](https://github.com/th33xitus/kiauh/issues/127).
Fail the webcamd service startup if there is no webcam present. 
If the script is allowed to restart the service every 10 seconds, the logs eventually fill up.

Don't restart webcamd service if fail.

---

scripts/install_klipper_webui.sh

GNU grep in Raspberry Pi OS doesn't seem to support `\d`.
https://www.gnu.org/software/grep/manual/grep.html

Use `[[:digit:]]` instead of `\d`

---

scripts/utilities.sh

This fixes the issue when there is no ini file present during first run and installing klipper.
The root cause is that the globals are read prior to creation of the ini file, but the code that initializes the globals is looking for the ini file via the read_kiauh_ini function. So we create the ini there on-demand if it's missing

Fix for issue #199

---

scripts/mainsail.sh

Mainsail has split its repositories and the configuration is now in its own repo. This fix aims to allow pulling the new configuration file which fixes Moonraker complaining about the gcode path not being correct : 
```
Moonraker warning
GCode path received from Klipper does not match expected location.
Received: '/home/pi/gcode_files'
Expected: '/home/pi/printer_data/gcodes'
Modify the [virtual_sdcard] section Klipper's configuration to correct this error.
[virtual_sdcard]
path: /home/pi/printer_data/gcodes
```

fix: pull mainsail.cfg from correct location

---

scripts/klipper.sh

Nowadays there is no reason to use Python 2. Current distros doesnt have python 2 support, also python 2 klipper installation lacks of unicode file support.
Let users to install python2 version of klipper for old os-es if they need.

refactor(klipper): recommend Python3 for Klipper installation

---

resources/moonraker.conf
scripts/obico.sh

Opt -s is now a default behavior for moonraker-obico/install.sh and hence it's deprecated.

refactor(obico): remove "-s" option from moonraker-obico/install.sh invocation

---

resources/moonraker-telegram-bot.service

Removed `RemainAfterExit`, as it is not needed for `Type=simple` service, and only cause problems.

fix(telegram bot): Fix service restart

---

resources/fluidd
resources/mainsail

An increased timeout needs to be set on API endpoint. Having default 60s means that, especially, on weaker/slower systems, and especially larger Gcode files with object exclusion configured, sending e.g. directly from slicer times out with HTTP 504. 600s seems like a reasonable number.

fix(mainsail): set increased read timeout on API endpoint

---

scripts/fluidd.sh
scripts/gcode_shell_command.sh
scripts/mainsail.sh
scripts/moonraker-telegram-bot.sh
scripts/moonraker.sh
scripts/nginx.sh
scripts/obico.sh
scripts/pretty_gcode.sh

My understanding from the usage of `\/home\/${USER}` around the scripts is to ensure that `/` is escaped to `\/`, but that makes the assumption that `${HOME}` is the same as `\home\${USER}`.
Knowing that we can use `${HOME//pattern/replacement}` we should be able to escape any `/` to `\/` by using `${HOME//\//\\/}`.
This change makes it possible to use Kiauh directly on a docker container with no "\home" folder.

fix: always use system home directory

---

scripts/crowsnest.sh

The crowsnest installer used `logname` to figure out the current user, this isn't great since it will return the "original" owner of the login session, so if you used `sudo` or `su` to become your klipper user .. it would try to install things into your original user making a bit of a mess ...
The symptoms show up similar to https://github.com/th33xitus/kiauh/issues/302 (not enough details in there to say its exactly the same)

fix(crowsnest): override installers BASE_USER to current user

---

scripts/klipper.sh

If a custom Klipper repository is not using 'master' as the branch checking for updates will fail or give stale data.
Fix this by checking the custom branch instead.

fix(klipper): if set, use custom branch to check for update

---

scripts/fluidd.sh
scripts/mainsail.sh

This allows the user to install remote mode Mainsail / Fluidd without Moonraker installed in order to setup separated web server from klipper host.
(1) When selecting to install Mainsail or Fluidd without Moonraker installed on localhost , it shows a prompt to confirm installing them without Moonraker.
(2) If installing a Mainsail, this setup remote-mode into the mainsail/config.json.
This is a re-implemented version of feature request #258 and closed PR #247.

feat: allow to install Mainsail/Fluidd without Moonraker

---

.gitignore
scripts/crowsnest.sh
scripts/klipper.sh
scripts/moonraker-telegram-bot.sh
scripts/moonraker.sh
scripts/octoeverywhere.sh
scripts/ui/install_menu.sh
scripts/ui/update_menu.sh
scripts/utilities.sh

Fixes #334 by first checking if any lists are more than 3 days old. Should be foolproof—if the check returns an error (e.g. if the `find` command or the `/var/lib/apt/lists` directory doesn't exist), it defaults to running the update.

refactor: update package lists only when stale

---

scripts/obico.sh

The primary purpose of this PR is to move dependency handling to "${MOONRAKER_OBICO_DIR}/install.sh", for both initial setup and upgrade, as we discussed on discord.
The 2nd part of this PR is to let user repair/reinstall a broken installation. This is less important. If you want, I can move it to a several PR.

refactor(obico): move dependency handling to obico's own install script

---

scripts/obico.sh
scripts/ui/main_menu.sh

Make the name consistent as 'Obico for Klipper' in all places where it's mentioned
Signed-off-by: Kenneth Jiang <kenneth.jiang@gmail.com>

refactor: make the 'Obico for Klipper' name consistent 

---

scripts/flash_klipper.sh

In *4) [Advanced]* --> *5) [Get MCU ID]* display the full path for USB connected MCUs instead of only the serial file name

refactor: show full path of mcu

---

resources/example.printer.cfg

This PR rename virtual_sd_card to virtual_sdcard in example.printer.cfg

fix: fix typo in example.printer.cfg

---

scripts/mobileraker.sh

With the PR https://github.com/Clon1998/mobileraker_companion/pull/77 I am switching to the installer of OE. 
Therefore, an update to the `mobileraker.sh` is required. I did not touch the removal code as it is pretty similar to what I am doing with the installer anyway.
Please wait with a merge on the PR until https://github.com/Clon1998/mobileraker_companion/pull/77 is ready

refactor(Mobileraker): update Mobileraker's companion installer script

---

scripts/backup.sh
scripts/globals.sh
scripts/spoolman.sh
scripts/ui/backup_menu.sh
scripts/ui/install_menu.sh
scripts/ui/main_menu.sh
scripts/ui/remove_menu.sh
scripts/ui/update_menu.sh

Hello, this PR adds support (install, update, remove, backup) for [Spoolman](https://github.com/Donkie/Spoolman) as it was requested in #373.
---
- The install script follows the [Spoolman docs](https://github.com/Donkie/Spoolman/blob/master/README.md#:~:text=sudo%20apt%2Dget,scripts/install.sh) and it has support for advanced configuration (only for the server's port at the moment)
- The update script follows the [Spoolman docs](https://github.com/Donkie/Spoolman/blob/master/README.md#:~:text=%23%20Stop%20and,rm%20%2Drf%20../Spoolman_old)
- The remove script deletes the Spoolman dir as well as the dir containing the SQLite db, cache and logs located by default in `~/.local/share/spoolman`
- The backup script copies both the Spoolman dir and the `~/.local/share/spoolman` into kiauh's …

feat: add Spoolman support

---

scripts/spoolman.sh
scripts/ui/remove_menu.sh

This PR fixes the issues reported by @dimitrisch in #477.
- `jq` has been replaced by `grep` using a regex to retrieve the local and remote Spoolman versions
- removed an extra space in the remove menu

fix: replace jq by grep to check Spoolman update

---

scripts/spoolman.sh

Checks if spoolman directory exists and if it doesn't the version check exits.

refactor: don't check spoolman version if not installed

---

kiauh.sh
scripts/utilities.sh

fix: detect RatOS 2.1+ as operating system and exit

---

scripts/moonraker.sh

A recent moonraker update broke KIAUHs parsing capabilities for the system dependencies.
This PR will fix the parsing and uses a different file for parsing the dependencies.
As soon as more distros are added to the file, this method needs to be checked again.
Fixes #489

fix: parse moonraker dependencies from system-dependencies.json

---

kiauh/components/klipper_firmware/menus/klipper_build_menu.py
kiauh/components/klipper_firmware/menus/klipper_flash_menu.py
kiauh/core/menus/__init__.py
kiauh/core/menus/base_menu.py
kiauh/utils/input_utils.py

This PR fixes #506 and improves some visuals of the various firmware related menus.
Visuals may not be perfect in all cases yet.

fix: y and n are invalid selections in KlipperFlashOverviewMenu

---

kiauh/extensions/obico/moonraker_obico_extension.py
kiauh/utils/instance_utils.py

As discussed in discord chat with @dw-0 , suffix "obico" needs to be removed from the blacklist so that moonraker_obico_extension can discover itself when calling get_instances.

fix: remove "obico" from the suffix_blacklist so that it can discover its own instances.

---

kiauh/extensions/obico/moonraker_obico.py

Without this fix, the `/home/pi/printer_data/systemd/moonraker-obico.env` would be generated as:
```
OBICO_ARGS="-m moonraker_obico.app -c /home/pi/printer_data/config//home/pi/printer_data/config/moonraker-obico.cfg"
```

fix: self.cfg_file is already a full path

---

kiauh/utils/config_utils.py

causes `[Errno 18] Invalid cross-device link` on tmpfs filesystems
fixes #509

fix: Path.rename() not working across devices

---

kiauh/core/menus/settings_menu.py
kiauh/procedures/system.py

Merge develop into master (Release v6.0.0-alpha.13)

---

scripts/moonraker.sh

This backports the Moonraker dependency fix to V5.    The python script that parses dependencies is inlined into the shell script.

fix: add support for Moonraker's dependency requirement specifiers to V5

---

kiauh/components/klipper/klipper_setup.py
scripts/klipper.sh

pkg-config is required for loading libusb header files to build rp2040 firmware
Signed-off-by: Andrey Kozhevnikov <coderusinbox@gmail.com>

fix: Add pkg-config to klipper packages

---

kiauh/utils/git_utils.py

This PR introduces an optional `blolbless` parameter to the `git_cmd_clone` function. When enabled, it adds the `--blolbless` flag to the git clone command. The function’s docstring has also been updated to document this new parameter.
- **New `blolbless` Parameter:**  
The `git_cmd_clone` function now accepts a boolean `blolbless` parameter. If set to `True`, it appends the `--blolbless` flag to the `git clone` command.
- **Updated Docstring:**  
The function’s documentation has been revised to include details about the new `blolbless` parameter.
- **Flexibility:**  
The new parameter allows users to enable or disable the `--blolbless` flag based on their specific needs or environment.
- **Clarity:**  
The updated docstring ensures that users are aware of the new parameter and understand …

feat(git_utils): Support for blolbless clone mode in git_cmd_clone

---

kiauh/utils/sys_utils.py

pip seems to write to stderr on warnings, caused by retries. even if the process exits with 0.

fix: exception raised on pip warning

---

kiauh/core/instance_manager/base_instance.py
scripts/moonraker.sh

Hello, I developer of moonraker-hmi service, that allows you to reuse old, unsupported by klipper, LCDs.
So, my service name detected as additional moonraker instance. It will be nice to exclude it from the list.
Also, moonraker-telegram-bot has same issue. I have added both to blacklist in this commit.

fix: add moonraker-hmi and moonraker-telegram-bot to the blacklist
